"""Add deleted_at field to mcp_servers

Revision ID: 066d83dc6198
Revises: 42b9370c1a05
Create Date: 2025-10-08 19:36:27.300929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066d83dc6198'
down_revision: Union[str, None] = '42b9370c1a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'deleted_at')
    # ### end Alembic commands ###
